// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
  {"name":"LMBS＿Motion","status":true,"description":"","parameters":{}}
];


//=============================================================================
/**
 * アイドリング（待機）アクション
 * @class LMBS_IdleAction
 * @constructor
 */

//-----------------------------------------------------------------------------
// LMBS_Window_TargetEnemy
//

function LMBS_Window_TargetEnemy() {
   this.initialize.apply(this, arguments);
}

LMBS_Window_TargetEnemy.prototype = Object.create(Window_Base.prototype);
LMBS_Window_TargetEnemy.prototype.constructor = LMBS_Window_TargetEnemy;

LMBS_Window_TargetEnemy.prototype.initialize = function() {
   Window_Base.prototype.initialize.call(this, 0, 0, 200, 80);
   this._enemy = null;
};

LMBS_Window_TargetEnemy.prototype.setEnemy = function(enemy) {
   this._enemy = enemy;
   this.refresh();
};

LMBS_Window_TargetEnemy.prototype.refresh = function() {
  this.contents.clear();
  if (this._enemy) {
    var lineHeight = this.lineHeight();
    //this.drawTextEx(this._text, this.textPadding(), 0);
  }
};

//-----------------------------------------------------------------------------
// LMBS_TargetCursor
//

function LMBS_TargetCursor() {
   this.initialize.apply(this, arguments);
}

LMBS_TargetCursor.prototype = Object.create(Sprite_Base.prototype);
LMBS_TargetCursor.prototype.constructor = LMBS_Window_TargetEnemy;

LMBS_TargetCursor.prototype.initialize = function() {
    Sprite_Base.prototype.initialize.call(this);
    this.bitmap = ImageManager.loadSystem('ButtonSet');
    this.anchor.x = 0.5;
    this.anchor.y = 1.0;
    this._frameCount = 0;
};

LMBS_TargetCursor.prototype.setPosition = function(x, y) {
    this.x = x;
    this.y = y;
}

LMBS_TargetCursor.prototype.update = function() {
    pattern = Math.floor(this._frameCount / 15);
    this._frameCount = (this._frameCount + 1) % 30;
    this.setFrame(48, pattern * 48, 48, 48);
};
