// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LMBS_Motion","status":true,"description":"","parameters":{}},
{"name":"LMBS_Actions","status":true,"description":"","parameters":{}},
{"name":"Box2D","status":true,"description":"","parameters":{}},
{"name":"three_min","status":false,"description":"","parameters":{}},
{"name":"three","status":false,"description":"","parameters":{}},
{"name":"LMBS_Physics","status":true,"description":"","parameters":{}},
{"name":"LMBS_Math","status":true,"description":"","parameters":{}},
{"name":"LMBS_Visuals","status":true,"description":"","parameters":{}},
{"name":"YEP_BattleEngineCore","status":false,"description":"","parameters":{}},
{"name":"LMBS","status":true,"description":"","parameters":{}},
{"name":"LMBS_Windows","status":true,"description":"","parameters":{}}
];
